<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.gedoplan.showcase</groupId>
    <artifactId>mp-lra-demo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>..</relativePath>
  </parent>

  <artifactId>mp-lra-room</artifactId>

  <!--
    We are switching the maven packaging type from war (default) to jar in quarkus profile.
  -->
  <packaging>${packaging.type}</packaging>

  <properties>
    <packaging.type>war</packaging.type>

  </properties>

  <dependencies>
    <dependency>
      <groupId>de.gedoplan</groupId>
      <artifactId>baselibs-persistence</artifactId>
      <version>10.1</version>
    </dependency>

  </dependencies>

  <build>
    <defaultGoal>package</defaultGoal>
    <finalName>${project.artifactId}</finalName>
  </build>

  <profiles>
    <profile>
      <id>jee_quarkus</id>

      <activation>
        <file>
          <exists>${basedir}/jee_quarkus</exists>
        </file>
      </activation>

      <properties>
        <packaging.type>jar</packaging.type>
      </properties>

      <dependencies>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-narayana-lra</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-rest-jackson</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
        <dependency>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
      </dependencies>
    </profile>

    <profile>
      <id>jee_standard</id>

      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>

      <dependencies>
        <dependency>
          <groupId>jakarta.platform</groupId>
          <artifactId>jakarta.jakartaee-api</artifactId>
          <version>${jakartaee-api.version}</version>
          <scope>provided</scope>
        </dependency>

        <dependency>
          <groupId>org.eclipse.microprofile</groupId>
          <artifactId>microprofile</artifactId>
          <version>${microprofile.version}</version>
          <type>pom</type>
          <scope>provided</scope>
        </dependency>

        <dependency>
          <groupId>org.eclipse.microprofile.lra</groupId>
          <artifactId>microprofile-lra-api</artifactId>
          <version>${microprofile-lra.version}</version>
          <scope>provided</scope>
        </dependency>


        <dependency>
          <groupId>org.jboss.logging</groupId>
          <artifactId>jboss-logging</artifactId>
          <version>${jboss-logging.version}</version>
        </dependency>
      </dependencies>

      <build>
        <plugins>
          <!-- Provision WildFly and enable dev mode (mvn wildfly-jar:dev-watch) -->
          <plugin>
            <groupId>org.wildfly.plugins</groupId>
            <artifactId>wildfly-jar-maven-plugin</artifactId>
            <configuration>
              <!-- 
              See parent for baseline configuration. 
              Additional layers can be added here with <layers>...</layers>.
              In order to replace the parent layers configuration completely, 
              use <layers combine.self="override">...</layers>.
              -->
              <layers>
                <layer>microprofile-lra-participant</layer>
                <layer>microprofile-platform</layer>
                <layer>microprofile-rest-client</layer>
              </layers>
              <cli-sessions>
                <cli-session>
                  <script-files>
                    <script>src/main/wildfly/cli/logging.cli</script>
                  </script-files>
                </cli-session>
              </cli-sessions>
              <debug>true</debug>
              <debugPort>8887</debugPort>
              <port>10090</port>
              <jvmArguments>
                <arg>-Djboss.bind.address=0.0.0.0</arg>
                <arg>-Djboss.socket.binding.port-offset=100</arg>
              </jvmArguments>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>
</project>